#!/bin/bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<EOF
-- Per-service roles and databases. Least privilege: no SUPERUSER, no CREATEDB after create.

DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${IMPRO_DB_USER}') THEN
    CREATE ROLE ${IMPRO_DB_USER} LOGIN PASSWORD '${IMPRO_DB_PASSWORD}';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${SYNAPSE_DB_USER}') THEN
    CREATE ROLE ${SYNAPSE_DB_USER} LOGIN PASSWORD '${SYNAPSE_DB_PASSWORD}';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${MAS_DB_USER}') THEN
    CREATE ROLE ${MAS_DB_USER} LOGIN PASSWORD '${MAS_DB_PASSWORD}';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${MAUTRIX_WHATSAPP_DB_USER}') THEN
    CREATE ROLE ${MAUTRIX_WHATSAPP_DB_USER} LOGIN PASSWORD '${MAUTRIX_WHATSAPP_DB_PASSWORD}';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${MAUTRIX_TELEGRAM_DB_USER}') THEN
    CREATE ROLE ${MAUTRIX_TELEGRAM_DB_USER} LOGIN PASSWORD '${MAUTRIX_TELEGRAM_DB_PASSWORD}';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${MAUTRIX_SIGNAL_DB_USER}') THEN
    CREATE ROLE ${MAUTRIX_SIGNAL_DB_USER} LOGIN PASSWORD '${MAUTRIX_SIGNAL_DB_PASSWORD}';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${MAUTRIX_INSTAGRAM_DB_USER}') THEN
    CREATE ROLE ${MAUTRIX_INSTAGRAM_DB_USER} LOGIN PASSWORD '${MAUTRIX_INSTAGRAM_DB_PASSWORD}';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${MAUTRIX_MESSENGER_DB_USER}') THEN
    CREATE ROLE ${MAUTRIX_MESSENGER_DB_USER} LOGIN PASSWORD '${MAUTRIX_MESSENGER_DB_PASSWORD}';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${MAUTRIX_DISCORD_DB_USER}') THEN
    CREATE ROLE ${MAUTRIX_DISCORD_DB_USER} LOGIN PASSWORD '${MAUTRIX_DISCORD_DB_PASSWORD}';
  END IF;
END
\$\$;

SELECT 'CREATE DATABASE ${IMPRO_DB_NAME} OWNER ${IMPRO_DB_USER} ENCODING ''UTF8'' LC_COLLATE ''C'' LC_CTYPE ''C'' TEMPLATE template0'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${IMPRO_DB_NAME}')\gexec
SELECT 'CREATE DATABASE ${SYNAPSE_DB_NAME} OWNER ${SYNAPSE_DB_USER} ENCODING ''UTF8'' LC_COLLATE ''C'' LC_CTYPE ''C'' TEMPLATE template0'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${SYNAPSE_DB_NAME}')\gexec
SELECT 'CREATE DATABASE ${MAS_DB_NAME} OWNER ${MAS_DB_USER} ENCODING ''UTF8'' LC_COLLATE ''C'' LC_CTYPE ''C'' TEMPLATE template0'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${MAS_DB_NAME}')\gexec
SELECT 'CREATE DATABASE ${MAUTRIX_WHATSAPP_DB_NAME} OWNER ${MAUTRIX_WHATSAPP_DB_USER} ENCODING ''UTF8'' LC_COLLATE ''C'' LC_CTYPE ''C'' TEMPLATE template0'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${MAUTRIX_WHATSAPP_DB_NAME}')\gexec
SELECT 'CREATE DATABASE ${MAUTRIX_TELEGRAM_DB_NAME} OWNER ${MAUTRIX_TELEGRAM_DB_USER} ENCODING ''UTF8'' LC_COLLATE ''C'' LC_CTYPE ''C'' TEMPLATE template0'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${MAUTRIX_TELEGRAM_DB_NAME}')\gexec
SELECT 'CREATE DATABASE ${MAUTRIX_SIGNAL_DB_NAME} OWNER ${MAUTRIX_SIGNAL_DB_USER} ENCODING ''UTF8'' LC_COLLATE ''C'' LC_CTYPE ''C'' TEMPLATE template0'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${MAUTRIX_SIGNAL_DB_NAME}')\gexec
SELECT 'CREATE DATABASE ${MAUTRIX_INSTAGRAM_DB_NAME} OWNER ${MAUTRIX_INSTAGRAM_DB_USER} ENCODING ''UTF8'' LC_COLLATE ''C'' LC_CTYPE ''C'' TEMPLATE template0'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${MAUTRIX_INSTAGRAM_DB_NAME}')\gexec
SELECT 'CREATE DATABASE ${MAUTRIX_MESSENGER_DB_NAME} OWNER ${MAUTRIX_MESSENGER_DB_USER} ENCODING ''UTF8'' LC_COLLATE ''C'' LC_CTYPE ''C'' TEMPLATE template0'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${MAUTRIX_MESSENGER_DB_NAME}')\gexec
SELECT 'CREATE DATABASE ${MAUTRIX_DISCORD_DB_NAME} OWNER ${MAUTRIX_DISCORD_DB_USER} ENCODING ''UTF8'' LC_COLLATE ''C'' LC_CTYPE ''C'' TEMPLATE template0'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${MAUTRIX_DISCORD_DB_NAME}')\gexec

GRANT ALL PRIVILEGES ON DATABASE ${IMPRO_DB_NAME} TO ${IMPRO_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${SYNAPSE_DB_NAME} TO ${SYNAPSE_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${MAS_DB_NAME} TO ${MAS_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${MAUTRIX_WHATSAPP_DB_NAME} TO ${MAUTRIX_WHATSAPP_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${MAUTRIX_TELEGRAM_DB_NAME} TO ${MAUTRIX_TELEGRAM_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${MAUTRIX_SIGNAL_DB_NAME} TO ${MAUTRIX_SIGNAL_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${MAUTRIX_INSTAGRAM_DB_NAME} TO ${MAUTRIX_INSTAGRAM_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${MAUTRIX_MESSENGER_DB_NAME} TO ${MAUTRIX_MESSENGER_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${MAUTRIX_DISCORD_DB_NAME} TO ${MAUTRIX_DISCORD_DB_USER};
EOF

# Synapse requires the uuid-ossp / pg_trgm extensions on some setups.
# Modern Synapse uses btree_gin/pg_trgm. Grant schema rights.
for pair in \
  "${SYNAPSE_DB_NAME}:${SYNAPSE_DB_USER}" \
  "${IMPRO_DB_NAME}:${IMPRO_DB_USER}" \
  "${MAS_DB_NAME}:${MAS_DB_USER}"; do
  db="${pair%%:*}"
  role="${pair##*:}"
  psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$db" <<SQL
GRANT ALL ON SCHEMA public TO ${role};
ALTER SCHEMA public OWNER TO ${role};
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gin;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
SQL
done

echo "Impro PostgreSQL databases initialized."
